### PR TITLE
Only populate the duplicate request check to 'yes' in case it's set as true

### PR DESCRIPTION
**Pull request by marjaimate**
Reference:
https://guides.wirecard.at/request_parameters#duplicaterequestcheck

### CODE REVIEW

**Comment by CHH** [comment]
Would you mind adding a test for that? Would be good to have a check if it's set to `false` that there got really no param added.

**Comment by marjaimate** [comment]
Sure thing, I'll add that

**Comment by marjaimate** [comment]
@CHH that's added now.

**Review by CHH — APPROVED** [review]

**Comment by CHH** [comment]
Thank you! 👏

**Pull request merged**
